name: yaggo
description: "Yag-go Burgers — App de Delivery"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/smash_classico.png
    - assets/images/double_smash.png
    - assets/images/urban_supremo.png
    - assets/images/chicken_crispy.png
    - assets/images/combo_classico.png
    - assets/images/combo_double.png
    - assets/images/combo_supremo.png
    - assets/images/milkshake_baunilha.png
    - assets/images/laranja.png
    - assets/images/refrigerante_lata.png
    - assets/images/brownie_quente.png
    - assets/images/sorvete_artesanal.png
